Correct return type of I2SCamera::dmaBufferInit
Lack of return statement in this function was causing compilation to fail:

C:\Users\per\AppData\Local\Temp\arduino_build_111040\sketch\I2SCamera.cpp: In static member function 'static bool I2SCamera::dmaBufferInit(int)':
I2SCamera.cpp:215: error: no return statement in function returning non-void [-Werror=return-type]

 }
 ^

cc1plus.exe: some warnings being treated as errors